version: '3.1'
volumes:
  postgres-data:
    driver: local

services:
  postgres:
      build: ./postgres/
      restart: always
      env_file:
      - './postgres/env.postgres'
      ports:
        - "5432:5432"
      container_name: postgres
      volumes:
        - ./postgres/data:/var/lib/postgresql/data
